# Generated by Django 5.0.6 on 2024-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.IntegerField()),
                ('City', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Register',
                'db_table': 'Register',
            },
        ),
    ]
